// Code generated by "stringer --type command --linecomment"; DO NOT EDIT.

package flaresolverr

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[createSession-0]
	_ = x[listSession-1]
	_ = x[destroySession-2]
	_ = x[requestGet-3]
	_ = x[requestPost-4]
}

const _command_name = "sessions.createsessions.listsessions.destroyrequest.getrequest.post"

var _command_index = [...]uint8{0, 15, 28, 44, 55, 67}

func (i command) String() string {
	if i < 0 || i >= command(len(_command_index)-1) {
		return "command(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _command_name[_command_index[i]:_command_index[i+1]]
}
